# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountEngine(object):
    def setupUi(self, AccountEngine):
        AccountEngine.setObjectName("AccountEngine")
        AccountEngine.resize(432, 432)
        AccountEngine.setMinimumSize(QtCore.QSize(432, 432))
        AccountEngine.setMaximumSize(QtCore.QSize(432, 432))
        AccountEngine.setStyleSheet("QWidget#AccountEngine{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 255, 127), stop:1 rgb(0, 85, 0))\n"
"}")
        self.label = QtWidgets.QLabel(AccountEngine)
        self.label.setGeometry(QtCore.QRect(140, 10, 141, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/Excel.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AccountEngine)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 281, 41))
        self.label_2.setStyleSheet("font: 75 italic 8pt \"Arial\";\n"
"font-size: 40px;\n"
"color: #fff;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(AccountEngine)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 411, 47))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setStyleSheet("font: 75 italic 8pt \"Arial\";\n"
"font-size: 16px;\n"
"color: #fff;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.filename = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.filename.setObjectName("filename")
        self.horizontalLayout.addWidget(self.filename)
        self.comenzar = QtWidgets.QPushButton(AccountEngine)
        self.comenzar.setGeometry(QtCore.QRect(150, 250, 141, 71))
        self.comenzar.setStyleSheet("border-radius: 20%;\n"
"background-color: rgb(170, 255, 255);\n"
"font-size: 20px")
        self.comenzar.setObjectName("comenzar")
        self.advices = QtWidgets.QLabel(AccountEngine)
        self.advices.setGeometry(QtCore.QRect(120, 340, 211, 61))
        self.advices.setStyleSheet("color: orangered; font-weight: bold; font-size: 20px")
        self.advices.setText("")
        self.advices.setAlignment(QtCore.Qt.AlignCenter)
        self.advices.setWordWrap(True)
        self.advices.setObjectName("advices")

        self.retranslateUi(AccountEngine)
        QtCore.QMetaObject.connectSlotsByName(AccountEngine)

    def retranslateUi(self, AccountEngine):
        _translate = QtCore.QCoreApplication.translate
        AccountEngine.setWindowTitle(_translate("AccountEngine", "Form"))
        self.label_2.setText(_translate("AccountEngine", "Account Engine"))
        self.label_3.setText(_translate("AccountEngine", "Nombre del Archivo de Excel"))
        self.comenzar.setText(_translate("AccountEngine", "Comenzar"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AccountEngine = QtWidgets.QWidget()
    ui = Ui_AccountEngine()
    ui.setupUi(AccountEngine)
    AccountEngine.show()
    sys.exit(app.exec_())
